<<<<<<< HEAD
= Cloud Misconfiguration Agent using Langchain and Neo4j
=======
= Build an Neo4j-backed Agentic AI Chatbot using Python to identify Cloud Misconfigurations
>>>>>>> 349a588 (final commit)

== Running the application

To run the application, you must install the libraries listed in `requirements.txt`.

[source,sh]
pip install -r requirements.txt


Then run the `streamlit run` command to start the app on link:http://localhost:8501/[http://localhost:8501/^].

[source,sh]
streamlit run bot.py

You can also run this application using Docker container engine:

[source,sh]
docker build -t cloud-misconfig-agent .
docker run -p 8501:8501 cloud-misconfig-agent

== Tests

To run the solution tests: 

. Create Neo4j instance with the `recommendations` dataset
. Run the link:https://raw.githubusercontent.com/neo4j-graphacademy/courses/refs/heads/main/asciidoc/courses/llm-chatbot-python/modules/3-tools/lessons/1-vector-tool/reset.cypher[Cypher to add embeddings and create the vector index^].
. Create a virtual environment and install the requirements.
+ 
[source,sh]
pip install -r requirements.txt
. Install `pytest`
+
[source,sh]
pip install pytest
. Create a `secrets.toml` file in the `.streamlit` directory. Use `secrets.toml.example` as a template.
. Run the tests
+
[source,sh]
pytest
