apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: default # Or your target namespace
type: Opaque
data:
  # Replace with the base64 encoded connection string: echo -n 'mongodb://tasky_user:YOUR_PASSWORD@DB_VM_IP:27017/taskydb' | base64
  MONGODB_URI: bW9uZ29kYjovL3Rhc2t5X3VzZXI6dGFza3lfcGFzc3dvcmRAMTAuMTI4LjAuMjQ6MjcwMTcvdGFza3lkYg==
  SECRET_KEY: c2VjcmV0MTIzYg==