name: Deploy Infrastructure (Terraform)

on:
  #push:
  #  branches:
  #    - main # Or your primary branch
  #  paths:
      # Adjust path if your terraform files are elsewhere
  #    - 'terraform/**'
  #    - '.github/workflows/infra_deploy_terraform.yml'
  workflow_dispatch: # Allow manual trigger

env:
  # Set your Terraform working directory
  TF_WORKING_DIR: terraform

permissions:
  contents: read
  id-token: write # Required for Workload Identity Federation

jobs:
  terraform:
    name: 'Terraform Plan & Apply'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        #credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      # with:
      #   terraform_version: <specific_version> # Optional: Pin version

    - name: Terraform Init
      id: init
      run: terraform init
      working-directory: ${{ env.TF_WORKING_DIR }}
      # Add backend config if using GCS/Terraform Cloud
      # run: terraform init -backend-config="bucket=${{ vars.TF_BACKEND_BUCKET }}"

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      working-directory: ${{ env.TF_WORKING_DIR }}

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -out=tfplan
      working-directory: ${{ env.TF_WORKING_DIR }}

    - name: Terraform Apply
      id: apply
      # Only apply on the main branch automatically
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve tfplan
      working-directory: ${{ env.TF_WORKING_DIR }}
